// The imagesdir attribute is only needed to display images during offline editing. Antora neglects the attribute.
:imagesdir: ../images

[[_phases_generalinformation]]
= Phases - General Information 
(((Phases)))  (((Phases ,General Information))) 

This appendix provides more detailed information on the IKAN ALM concept of "`Phases`".

When IKAN ALM is running Level Requests, Builds and Deploys, all actions are performed by executing a sequence of Phases.

Phases represent specific tasks or actions that must be performed by the system.

Phases are defined in the IKAN ALM database and can be consulted and manipulated in the Phases section of the Global Administration interface.
Once they have been defined in Global Administration, Phases may be linked to Levels, Build or Deploy Environments in the Project Administration context.

Phases are categorized into different types depending on who created them ("`Core`" and "`Custom`" Phases) and where they are used (Level, Build and Deploy Phases).

The IKAN ALM core functionality is performed by so-called "Core" Phases.
Those Core Phases can only be viewed, and cannot be altered nor deleted.
Consider them an integral part of IKAN ALM.
When you create a new Level, Build or Deploy Environment, its default workflow will be created and will completely consist of a sequence of Core Phases.
Next, you may change this default workflow by removing Core Phases, by changing the sequence order or by adding your own Phases.

Those own Phases are also called "`Custom`" Phases.
You may create them from scratch in Global Administration, based on one or more working scripts and resources, or you can import an existing Custom Phase, using the "`Import Phase`" functionality.

We also distinguish 3 types of Phases in IKAN ALM, depending on where they are being used:

* <<App_Phases.adoc#_phases_levelphases,Level Phases>>: phases inserted into the Level workflow. They will be executed on the IKAN ALM Server.
* <<App_Phases.adoc#_phases_buildphases,Build Phases>>: phases inserted into the Build Environment workflow. They will be executed on an IKAN ALM Agent.
* <<App_Phases.adoc#_phases_deployphases,Deploy Phases>>: phases inserted into the Deploy Environment workflow. They will be executed on an IKAN ALM Agent.


A Level Request represents the execution of a Level.
A Level is split up into Level Phases.
Those Phases will be executed sequentially, and when all Phases have completed, the Level Request has ended.
One of the Phases of a Level Request is the Build Phase, which will execute the Builds related to this Level Request.
A Build represents the execution of a Build Environment.
These Builds, for their part, are split up into Build Phases.
When all the defined Build phases in the Build have executed successfully, the Build was successful.
The Deploys of a Level Request are handled similarly.

[NOTE]
====
From IKAN ALM 5.5 onwards, there is no strict boundary anymore between those three types of Phases.
The Core "`Execute Script"` Phase, is as well a Level as a Build or Deploy Phase, since you may use it on a Level, Build or Deploy Environment.
Also, when you create a Custom Phase, you define where the Phase may be used: on a Level, on a Build Environment or on a Deploy Environment (or on all three Environments). In this context, we consider the Level to be also an "Environment".
====

All types of Phases inserted into the workflow of a Level/Build/Deploy Environment have the following general fields:

[cols="1,1", frame="topbot", options="header"]
|===
| Field
| Description

|Phase Name
|This field corresponds to the Display Name of the Phase definition and, at the same time, defines its function.

|Phase Version
|This field, together with the Phase name, forms the unique identifier of the Phase.
The version of the Core Phases matches the IKAN ALM version (e.g., 5.5.0).

The version of Custom Phases conforms to the format as explained in the section <<GlobAdm_Phases.adoc#_globadm_phases_creating,Creating a Phase Definition>>.

|Next Phase On Success (Phase Position)
|This field defines which Phase should be executed next if the current Phase completes successfully.
It can`'t be edited directly; its value is inferred by the order in the Phase sequence of the Level/Build Environment/Deploy Environment.

|Next Phase On Error
|This field defines which Phase should be executed next if the current Phase has gone in Error. 

Usually this Phase is a Cleanup Phase.

|Fail On Error
a|This field defines whether the status of the enclosing Level Request, Build or Deploy should be set to Fail or to Warning when this Phase goes in Error.

Possible values:

* __Yes__: set this to _Yes_ when the Phase is critical (e.g., a Retrieve Code Phase, an Execute Build Script Phase, a Custom Compile Sources Phase, ...). The Level Request, Build or Deploy status will be set to __Fail__.
* __No__: set this to _No_ for a non-critical Phase (e.g., a Cleanup Build Result Phase, a Custom Test Phase, ...). The Level Request, Build or Deploy status will be set to __Warning__.

|===


For more information on defining and configuring Phases, refer to the following sections: 

* <<ProjAdm_Levels.adoc#_plevelenvmgt_editlevelphases,Editing a Level Phase>> 
* <<ProjAdm_BuildEnv.adoc#_projadm_buildenv_editphase,Editing a Build Environment Phase>>, 
* <<ProjAdm_DeployEnv.adoc#_projadm_deployenv_phaseedit,Editing a Deploy Environment Phase>>, 
* <<GlobAdm_Phases.adoc#_globadm_phases_creating,Creating a Phase Definition>>
* <<GlobAdm_Phases.adoc#_globadm_phases_editing,Editing a Phase Definition>>

When executing a Phase, it can have the following status:

[cols="1,1", frame="topbot", options="header"]
|===
| Status
| Description

|Success
|The Phase finished successfully

|Warning
|The Phase finished with a warnings

|Fail
|The Phase failed

|Running
|The Phase is currently being executed

|Not executed
|The Phase has not been executed

|Aborted
|The Phase was aborted
|===


The execution of a Phase can be viewed on the <<Desktop_LevelRequests.adoc#_desktop_lr_phaselogs,Phase Logs>> tab page on the __Level Request Detail__ screen.

[[_phases_levelphases]]
== Level Phases 
(((Levels ,Phases)))  (((Phases ,Level Phases))) 

Level Phases are the actions that must be performed to complete a Level Request.

A vanilla IKAN ALM installation only contains Level Phases of the "`Core`" type.
You can search for them in the _Phases
Overview_ by restricting the search to Core Phases that can be used on a Level.
Next to those Core Phases, you may enrich the functionality of IKAN ALM by creating your own Custom Phases which can be used on a Level.

Level Phases may be inserted into the workflow of a Level (<<ProjAdm_Levels.adoc#_levelenvmgt_levelphases,Level Phases>>) and are logged on the __Phase Logs__ panel of the __Level
Request Detail__ screen (<<Desktop_LevelRequests.adoc#_desktop_lr_phaselogs_levelphases,Level Phases>>).

They are executed by the Monitor Thread of the IKAN ALM Server, so they run on the IKAN ALM Server Machine!

Their exact behavior may depend on the Level Type, and on the status of previously executed Level Phases.

The following section describes each of the Core Level Phases in detail:

* <<App_Phases.adoc#_phases_levelphases_retrievecode,Retrieve Code Phase>>
* <<App_Phases.adoc#_phases_levelphases_build,Build Phase>>
* <<App_Phases.adoc#_phases_levelphases_tagcode,Tag Code Phase>>
* <<App_Phases.adoc#_phases_levelphases_deploy,Deploy Phase>>
* <<App_Phases.adoc#_phases_levelphases_issuetracking,Issue Tracking Phase>>
* <<App_Phases.adoc#_phases_levelphases_linkfilerevisions,Link File Revisions>>
* <<App_Phases.adoc#_phases_levelphases_cleanupworkcopy,Cleanup Work Copy Phase>>
* <<App_Phases.adoc#_phases_levelphases_executescriptphase,Execute Script Phase>>


Next to the Core Level Phases, you can create your own Custom Level Phases:

* <<App_Phases.adoc#_phases_levelphases_customlevelphase,Custom Level Phase>>


[[_phases_levelphases_retrievecode]]
=== Retrieve Code Phase 
(((Phases ,Level Phases ,Retrieve Code))) 

The _Retrieve Code_ Phase is usually the first Phase executed in a Level Request.
It retrieves (checks out) the source code from the VCR and copies it to the Transport Location (sub folder of the Work Copy Location) where it is accessible for the Agents running the Builds of the Level Request.

When the Level Request is for a Build Level, the latest source code is checked out; when it is for a Test Level, the tagged source code is retrieved.

When the Level Request is for a Build Level attached to a Tag-based Project Stream, the source code is retrieved that was tagged with the tag specified in the _VCR Tag_ field when the Level Request was created.
See the description of the _VCR
Tag_ field in the section <<Desktop_LevelRequests.adoc#_desktop_lr_createlevelrequest_build,Creating a Build Level Request>>.

The _Retrieve Code_ Phase also retrieves the source code and/or the build results of all Child Builds this Level Request is depending on.
See <<Desktop_LevelRequests.adoc#_desktop_lr_viewdependency,Build Dependencies>>.

In the case of a Partial Build, (<<ProjAdm_ProjMgt_ProjectStream.adoc#_projadmin_projectstream_createbranch,Creating a Branch Project Stream>>), only the modified source code will be retrieved and made available to the Agents running the Builds of the Level Request.

The _alm.phase.retrieve.source.partialBuild.partialCheckout_ (Environment) Phase Parameter defines how this is done: if it is set to _true_ (default value) and if the VCR supports it (currently only Subversion), this is done by a partial checkout of the modified sources.
Otherwise, all sources will be checked out, but only the modified sources will be transported to the source location of the Build Environment.

When the Level Request has no Builds associated with it, the _Retrieve Code_ Phase does nothing and exits with status __Success__.
In that case, you could remove the _Retrieve Code_ Phase from the Level`'s workflow.

[[_phases_levelphases_build]]
=== Build Phase 
(((Phases ,Level Phases ,Build))) 

The _Build_ Phase activates and monitors the execution of the Builds of the Level Request.

When it starts, it activates the Builders running on the Agent Machines to start all the waiting Builds of the Level Request.
Then, it waits for all the Builds to finish.

Meanwhile, when a Level Request is aborted while in the Build Phase, the Build Phase notifies and stops the executing Builders.

When all Builds have finished, the status of the Build Phase is set, depending on the statuses of the Builds:

* When a Build has failed, the status of the Build Phase is set to __Error__,
* When no Builds have failed, but one Build ended with status __Warning__, the status of the Build Phase is set to _Warning_
* When all Builds executed successfully, the status of the Build Phase is set to __Success__.


When no Builds have been defined for the Level Request, the _Build_ Phase does nothing and exits with status __Success__.
In that case, you could remove the _Build_ Phase from the Level`'s workflow.

[[_phases_levelphases_tagcode]]
=== Tag Code Phase 
(((Phases ,Level Phases ,Tag Code))) 

The _Tag Code_ Phase tags the code that was checked out with the VCR Tag associated with the Level Request.
When the tag already exists in the VCR, the tag is moved.

The _Tag Code_ Phase only tags when the checked-out code was the latest code of the VCR branch.
So, it won`'t tag for a Build Level in a Tag Based Project Stream, and it won`'t (re-)tag for a Deliver Level Request.
In both of those cases, tagged code was checked out, so no tagging was needed, and you could remove the _Tag Code_ Phase from the Level`'s workflow.

[[_phases_levelphases_deploy]]
=== Deploy Phase 
(((Phases ,Level Phases ,Deploy))) 

The _Deploy Phase_ activates and monitors the execution of the Deploys of the Level Request.

When it starts, it activates the Deployers running on the Agent Machines to start all the waiting Deploys of the Level Request with Sequence Number ``0``.
Next, it waits for all those Deploys to finish.
Next, when those Deploys all ended with status _Success_ or __Warning__, it activates the Deploys that have Sequence Number ``1``, and so on until there are no more Deploys or a Deploy has failed.

Meanwhile, when a Level Request is aborted while in the Deploy Phase, the Deploy Phase notifies and stops the executing Deployers.

When all Deploys have finished, the status of the Deploy Phase is set, depending on the statuses of the Deploys:

* When a Deploy has failed, the status of the Deploy Phase is set to __Error__,
* When no Deploys have failed, but one Deploy ended with status __Warning__, the status of the Deploy Phase is set to _Warning_
* When all Deploys executed successfully, the status of the Deploy Phase is set to __Success__.


When no Deploys have been defined for the Level Request, the _Deploy_ Phase does nothing and exits with status __Success__.
In that case, you could remove the _Deploy_ Phase from the Level`'s workflow.

[[_phases_levelphases_issuetracking]]
=== Issue Tracking Phase 
(((Phases ,Level Phases ,Issue Tracking))) 

The _Issue Tracking_ Phase links Issues, managed in an external Issue Tracking System, with a Level Request, by searching for references to the Issues in the commit comments of the VCR.

In the case of a Build Level Request, the Issue Tracking Phase parses the commit comments that have been entered since the last successful Level Request for that Level and tries to match the Issue Pattern of the attached Issue Tracking System (<<GlobAdm_IssueTracking.adoc#_globadm_issuetrackingcreate,Creating an Issue Tracking System>>). All found Issues will be attached to the Level Request.

For an Atlassian JIRA, HP Quality Center or CollabNet TeamForge Issue Tracking System, the Issue Tracking Phase will also connect to and try to identify the issues in JIRA, HP ALM or TeamForge.
For each identified Issue, it will try to get additional information from JIRA, HP ALM or TeamForge (like description, status, owner and priority) and store it in IKAN ALM.

When the Level Request is a Deliver Level Request, the Issue Tracking Phase enumerates all the Issues that have been attached to the previous successful Build Level Requests that have occurred since the last successful Deliver Level Request on this Level, and adds all of them to this Level Request.

For example:

Suppose we have built the following Builds: Build 3 with Issue 3, Build 4 with Issue 4, Build 5 with Issue 5 and 6.
Previously, Build 2 was delivered.
If we now deliver Build 5, Issues 3,4,5 and 6 will be attached to the Deliver Level Request.

For an Atlassian JIRA, HP ALM or TeamForge Issue Tracking System, the Issue Tracking Phase will also synchronize all the issues attached to the Deliver Level Request: it will compare the info about the issue in IKAN ALM with the current information in JIRA, HP ALM or TeamForge and update description, status, owner or priority if necessary.

If the Level Request was not successful, the Issue Tracking Phase does nothing, and exits with status __Success__, reporting that it did not process any Issues.

When no Issue Tracking System was attached to the Project of this Level Request, the Issue Tracking Phase does nothing, and exits with status __Success__.

[NOTE]
====
When you attach an Issue Tracking System to a Project after it has been created, you must manually add the Issue Tracking Phase to the Levels you want Issue Tracking to be performed on.
====

[[_phases_levelphases_linkfilerevisions]]
=== Link File Revisions 
(((Phases ,Level Phases ,Link File Revisions))) 

The _Link File Revisions_ Phase links the involved File Revisions to the Level Request. 

For a Build Level Request this is done based on the File Revisions that have been checked out from the VCR during the _Retrieve
Code_ Phase. 

For a Deliver or Rollback Level Request, this is done based on the File Revisions linked to the Level Request (from the previous Level) that will be delivered or rollbacked.
Although these File Revisions are also linked to the Package, this Phase is necessary in order to take a snapshot of the Package content at Level Request execution time, since this content will probably change in time.

As this Phase is only applicable to Level Requests for Packages, it will only appear in the Levels of Package-based Projects.

[[_phases_levelphases_cleanupworkcopy]]
=== Cleanup Work Copy Phase 
(((Phases ,Level Phases ,Cleanup Work Copy))) 

The _Cleanup Work Copy_ Phase cleans up the Work Copy Location where the sources of the Level Request were checked out. 

It fails when it can`'t find the folder.
Typically, this Phase`'s Fail On Error flag is set to '`No`', causing the Level Request to end with status _Warning_ instead of _Fail_ when this Phase goes in error.

If the Level has its _Debug_ flag set to "`Yes`", the _Cleanup Work Copy_ Phase does nothing, and exits with status __Error__, reporting that the _Debug_ flag was set for the Level.

[[_phases_levelphases_executescriptphase]]
=== Execute Script Phase 
(((Phases ,Level Phases ,Execute Script Phase))) 

The _Execute Script_ Phase executes a script on the IKAN ALM Server Machine using the specified Scripting Tool and the pre-defined Level Parameters.
Both the script (alm.phase.mainScript) and the Scripting Tool (alm.phase.builder) must be defined by a mandatory Phase Parameter after inserting this Phase into a Level.

The _Execute Script_ Phase has been introduced on the Level from IKAN ALM 5.5 onwards, together with the Custom Phase.
The log generated by the script is saved in the IKAN ALM database.
Note that this Phase is never inserted into the default workflow of a Level (i.e., when creating a new Level from scratch).

When the script is executed successfully, the _Execute
Script_ Phase exits with status __Success__.
If not, it exits with status _Error_ and logs the errors on the _Phase Logs_ panel of the _Level
Request Detail_ screen (<<Desktop_LevelRequests.adoc#_desktop_lr_phaselogs_levelphases,Level Phases>>).

Next to the Core Phases, you may define your own Phases in Global Administration (<<GlobAdm_Phases.adoc#_globadm_phases_creating,Creating a Phase Definition>>) and specify that they may be used on a Level.
Once inserted into the workflow of a Level, we call them Custom Level Phases.

[[_phases_levelphases_customlevelphase]]
=== Custom Level Phase 
(((Phases ,Level Phases ,Custom Level Phase))) 

[NOTE]
====
The Display Name of a Custom Level Phase, as defined in Global Administration and provided by the creator of the Custom Phase, is used in the ALM interface when inserting it into a Level or viewing the log on the __View Level Request Log __screen.
So, the name displayed could be something like "`Retrieve from Archive`" or "`Filter Sources`".
====

A _Custom Level_ Phase executes a script on the IKAN ALM Server Machine using the specified Scripting Tool and the pre-defined Level Parameters.
The Display Name of this Phase and the executed script (alm.phase.mainScript) are specified in the definition of this Custom Phase in Global Administration.
The Scripting Tool (alm.phase.builder) that executes the script depends on the Execution Type of the Phase definition and its value must be set after inserting this Phase into a Level.

The Custom Level Phase has been introduced from IKAN ALM 5.5 onwards, together with the _Execute Script_ Phase.
The log generated by the script is saved in the IKAN ALM database.
Note that this Phase is never inserted into the default workflow of a Level (i.e., when creating a new Level from scratch).

When the script is executed successfully, the _Custom
Level_ Phase exits with status __Success__.
If not, it exits with status _Error_ and logs the errors on the _Phase Logs_ panel of the _Level
Request Detail_ screen (<<Desktop_LevelRequests.adoc#_desktop_lr_phaselogs_levelphases,Level Phases>>).

[NOTE]
====
A Custom Level Phase may also be a Custom Build or Deploy Phase: the definition in Global Administration can also specify that it may be used on a Build or Deploy Environment.
====

[[_phases_buildphases]]
== Build Phases 
(((Phases ,Build Phases))) 

Build Phases are the actions that must be performed to complete a Build.
A vanilla IKAN ALM installation only contains Build Phases of the "`Core`" type.
You can search for them in the __Phases Overview__, by restricting the search to Core Phases that can be used on a Build Environment.
Next to those Core Phases, you may enrich the functionality of IKAN ALM by creating your own Custom Phases that can be used on a Build Environment.

Build Phases may be inserted into a Build Environment (<<ProjAdm_BuildEnv.adoc#_projadm_buildenv_phases,Build Environment Phases>>). Their actions during the handling of a Build are logged on the __Phase Logs__ tab page of the __Level Request Detail__ screen (<<Desktop_LevelRequests.adoc#_desktop_lr_phaselogs_buildactions,Build Actions>>). 

They are executed by the Builder Thread of the IKAN ALM Agent, so they run on an IKAN ALM Agent Machine!

The following section describes each of the Core Build Phases in detail:

* <<App_Phases.adoc#_babfgbhf,Transport Source Phase>>
* <<App_Phases.adoc#_babcijhh,Verify Build Script Phase>>
* <<App_Phases.adoc#_phases_buildphases_executebuildscript,Execute Script Phase>>
* <<App_Phases.adoc#_phases_buildphases_transportdesployscript,Transport Deploy Script Phase>>
* <<App_Phases.adoc#_phases_buildphases_transportpackagerersults,Transport Package Results Phase>>
* <<App_Phases.adoc#_phases_buildphases_compressbuild,Compress Build Phase>>
* <<App_Phases.adoc#_phases_buildphases_archiveresult,Archive Result Phase>>
* <<App_Phases.adoc#_phases_buildphases_cleanupsource,Cleanup Source Phase>>
* <<App_Phases.adoc#_phases_buildphases_cleanupresult,Cleanup Result Phase>>


Next to the Core Build Phases, you can create your own Custom Build Phases:

* <<App_Phases.adoc#_phases_buildphases_custombuildphase,Custom Build Phase>>


[[_babfgbhf]]
=== Transport Source Phase 
(((Phases ,Build Phases ,Transport Source))) 

The _Transport Source_ Phase transports the Source code and, possibly, the build results of Child Projects from the Work Copy Location on the IKAN ALM Server Machine to the Build Environment Source Location on the IKAN ALM Agent Machine, using the Transporter associated with the IKAN ALM Agent Machine.

When doing a Partial Build, the Transport Source Phase may also transport the build results of the previous Build from the Build Archive Location on the IKAN ALM Server Machine to the Environment`'s Source Location on the IKAN ALM Agent Machine.
Set the __alm.phase.transport.source.partialBuild.copyPreviousBuildResult __(Environment) Phase Parameter to _true_ to obtain this behavior.
Note that the default value of this Parameter is __false__.

See also <<App_Phases.adoc#_phases_levelphases_retrievecode,Retrieve Code Phase>>.

[[_babcijhh]]
=== Verify Build Script Phase 
(((Phases ,Build Phases ,Verify Build Script))) 

The _Verify Build Script_ Phase tries to locate the defined Build Script, and fails if it cannot.

First, it determines what Build Script to look for.
If there`'s a Build Script defined on the Build Environment (<<ProjAdm_BuildEnv.adoc#_pcreatebuildenvironment,Creating a Build Environment>>), it will try to find that.
If not, it will look for the Build Script defined on the Project (<<ProjAdm_Projects.adoc#_projadmin_projectsoverview_editing,Editing Project Settings>>).

Then, it tries to find the Build Script in the Build Environment`'s Source Location.

If not found, it tries to copy the Build Script from the IKAN ALM Script Location as defined in the <<GlobAdm_System.adoc#_globadm_system_settings,System Settings>>.

If not found there either, the Verify Build Script Phase exits with status __Error__.

If found, the Verify Build Script Phase exits with status __Success__, and reports where it located the Build Script.

[[_phases_buildphases_executebuildscript]]
=== Execute Script Phase 
(((Phases ,Build Phases ,Execute Script))) 

The _Execute Script_ Phase executes the Build Script on the defined Machine using the specified Scripting Tool and the defined Build Parameters. 

It saves the Build log generated by the Build Script in the IKAN ALM database.

When the Build Script is executed successfully, the _Execute
Script_ Phase exits with status __Success__.
If not, it exits with status _Error_ and logs the errors on the _Phase Logs_ panel of the _Level
Request Detail_ screen (<<Desktop_LevelRequests.adoc#_desktop_lr_phaselogs_buildactions,Build Actions>>).

[[_phases_buildphases_transportdesployscript]]
=== Transport Deploy Script Phase 
(((Phases ,Build Phases ,Transport Deploy Script))) 

The _Transport Deploy Script_ Phase copies the Deploy Scripts that are defined in the Deploy Environments linked to the Build Environment of this Build from the Build Environment`'s Source Location to the Target Location. 

This action is performed, so that the Deploy Scripts are included in the compressed Build File created by the Compress Build Phase.

[[_phases_buildphases_transportpackagerersults]]
=== Transport Package Results Phase 
(((Phases ,Build Phases ,Transport Deploy Script))) 

This Phase is only relevant for Package Builds.

If the Package is part of a Package Build Group, it will retrieve the latest Build Results of some (or all, dependent on the configuration of the Package Build Group) of the Packages in the Package Build Group.
It will use the Transporter defined for the Agent to transport the Results from the IKAN ALM Build Archive on the IKAN ALM Server to the $\{sourceRoot}/packages directory on the Build Environment.
The Phase also creates a _PackageBuildGroup.xml_ file in the $\{sourceRoot}/packages directory on the Build Environment that can be used as input in later Phases, e.g., for the Mainframe Compilation workflow, to transfer these Build Results and build up the correct PDS structure on the Mainframe. 

The _Retrieve All Build Results_ attribute of the Package Build Group, and the setting of the Dependency Level of the Packages in the Package Build Group determine which Build Results will be retrieved: the latest build results of all Packages in the Package Build Group in case _Retrieve All Build Results_ has been set to __true__, or only the latest Build Results of Packages with a lower Dependency Level in case _Retrieve
All Build Results_ has been set to __false__.

[[_phases_buildphases_compressbuild]]
=== Compress Build Phase 
(((Phases ,Build Phases ,Compress Build))) 

The _Compress Build_ Phase compresses the Build result files in the Build Environment`'s Target Location.

If the Agent Machine runs a Windows OS, the Compress Build Phase creates a `$$.$$zip` file, otherwise it creates a `$$.$$tar.gz` file

[[_phases_buildphases_archiveresult]]
=== Archive Result Phase 
(((Phases ,Build Phases ,Archive Result))) 

The _Archive Result_ Phase transports the compressed Build file from the Build Environment`'s Target Location on the IKAN ALM Agent Machine to the Build Archive Location on the IKAN ALM Server Machine, using the Transporter associated with the IKAN ALM Agent Machine.

[[_phases_buildphases_cleanupsource]]
=== Cleanup Source Phase 
(((Phases ,Build Phases ,Cleanup Source))) 

The _Cleanup Source_ Phase deletes all files in the Build Environment`'s Source Location.

If the Build Environment has its Debug flag set to '`Yes`', the Cleanup Source Phase does nothing, and exits with status __Error__, reporting that the Debug flag was set in the Build Environment.

[[_phases_buildphases_cleanupresult]]
=== Cleanup Result Phase 
(((Phases ,Build Phases ,Cleanup Result))) 

The _Cleanup Result_ Phase deletes all files in the Build Environment`'s Target Location.

If the Build Environment has its Debug flag set to '`Yes`', the Cleanup Result Phase does nothing, and exits with status __Error__, reporting that the Debug flag was set in the Build Environment.

Next to the Core Phases, you may define your own Phases in Global Administration (<<GlobAdm_Phases.adoc#_globadm_phases_creating,Creating a Phase Definition>>) and specify that they may be used on a Build Environment.
Once inserted into the workflow of a Build Environment, we call them Custom Build Phases.

[[_phases_buildphases_custombuildphase]]
=== Custom Build Phase 
(((Phases ,Build Phases ,Custom Build Phase))) 

[NOTE]
====
The Display Name of a Custom Build Phase, as defined in Global Administration and provided by the creator of the Custom Phase, is used in the ALM interface when inserting it into a Build Environment or viewing the log on the _View Build Phases Log_ screen.
So, the name displayed could be something like "`Generate Documentation`" or "`Run Unit Tests`".
====

The _Custom Build_ Phase executes a script on the IKAN ALM Agent Machine using the specified Scripting Tool and the defined Build Parameters.
The Display Name of this Phase and the executed script (alm.phase.mainScript) are specified in the definition of this Custom Phase in Global Administration.
The Scripting Tool (alm.phase.builder) that executes the script depends on the Execution Type of the Phase definition.
When this Execution Type differs from the Scripting Tool linked to the Build Environment, its value must be set after inserting this Phase into a Build Environment.

The _Custom Build_ Phase has been introduced from IKAN ALM 5.5 onwards.
The log generated by the script is saved in the IKAN ALM database.
Note that this Phase is never inserted into the default workflow of a Build Environment (i.e., when creating a new Build Environment from scratch).

When the script is executed successfully, the _Custom
Build_ Phase exits with status __Success__.
If not, it exits with status _Error_ and logs the errors on the _Phase Logs_ panel of the _Level
Request Detail_ screen (<<Desktop_LevelRequests.adoc#_desktop_lr_phaselogs_buildactions,Build Actions>>).

[NOTE]
====
A Custom Build Phase may also be a Custom Level or Deploy Phase: the definition in Global Administration can also specify that it may be used on a Level or Deploy Environment.
====

[[_phases_deployphases]]
== Deploy Phases 
(((Phases ,Deploy Phases))) 

Deploy Phases are the actions that must be performed to complete a Deploy.
A vanilla IKAN ALM installation only contains Deploy Phases of the "`Core`" type.
You can search for them in the __Phases
Overview__, by restricting the search to Core Phases that can be used on a Deploy Environment.
Next to those Core Phases, you may enrich the functionality of IKAN ALM by creating your own Custom Phases that can be used on a Deploy Environment.

Deploy Phases may be inserted into a Deploy Environment (<<ProjAdm_DeployEnv.adoc#_projadm_deplanv_phases,Deploy Environment Phases>>) and their actions during the handling or a Deploy are logged on the __Phase Logs__ tab page of the __Level Request Detail__ screen (<<Desktop_LevelRequests.adoc#_desktop_lr_phaselogs_deployactions,Deploy Actions>>). 

They are executed by the Deployer Thread of the IKAN ALM Agent, so they run on an IKAN ALM Agent Machine!

[NOTE]
====
The number of running Deploys on an IKAN ALM Agent is managed by specifying the _Concurrent Deploy
Limit_ attribute for the Machine representing the IKAN ALM Agent.
By default, this limit is set to __0__, meaning that all Deploys on the Agent will run concurrently (i.e., in parallel). 

If another number is specified, a Deploy can only be started if there are not more running Deploys as indicated.
So if the number is limited to 1, this means that all deploys will run sequentially on the Agent.
If the number is set to 2, only 2 deploys can run concurrently, meaning that if there is a third Deploy with status _Ru,n_ , this third one will be added to a "`Waiting queue`" and it will only be started if one of the other (running) Deploys has finished.
====

The following section describes each of the Core Deploy Phase in detail:

* <<App_Phases.adoc#_phases_deployphases_transportbuildresult,Transport Build Result Phase>>
* <<App_Phases.adoc#_phases_deployphases_decompressbuildresult,Decompress Build Result Phase>>
* <<App_Phases.adoc#_phases_deployphases_verifydeployscript,Verify Deploy Script Phase>>
* <<App_Phases.adoc#_phases_deployphases_executedeployscript,Execute Script Phase>>
* <<App_Phases.adoc#_phases_deployphases_cleanupbuidlresult,Cleanup Build Result Phase>>


Next to the Core Deploy Phases, you can create your own Custom Deploy Phases:

* <<App_Phases.adoc#_phases_deployphases_customdeployphase,Custom Deploy Phase>>


[[_phases_deployphases_transportbuildresult]]
=== Transport Build Result Phase 
(((Phases ,Deploy Phases ,Transport Build Result))) 

The _Transport Build Result_ Phase transports the Build result from the Build Archive Location on the IKAN ALM Server Machine to the Deploy Environment Source Location on the IKAN ALM Agent Machine, using the Transporter associated with the IKAN ALM Agent Machine.

When doing a Partial Deploy, only the modified and added files in the Build result are transferred.
See the description of the _Partial Deploy_ field in the section <<ProjAdm_DeployEnv.adoc#_pcreatedeployenvironment,Creating a Deploy Environment>>.

[[_phases_deployphases_decompressbuildresult]]
=== Decompress Build Result Phase 
(((Phases ,Deploy Phases ,Decompress Build Result))) 

The _Decompress Build Result_ Phase decompresses the Build result file that was transported by the Transport Build Result Phase into the Deploy Environment`'s Source Location, and afterwards, deletes the Build result file.

[[_phases_deployphases_verifydeployscript]]
=== Verify Deploy Script Phase 
(((Phases ,Deploy Phases ,Verify Deploy Script))) 

The _Verify Deploy Script_ Phase tries to locate the defined Deploy Script, and fails if it cannot.

First, it determines what Deploy Script to look for.
If there`'s a Deploy Script defined on the Deploy Environment (<<ProjAdm_DeployEnv.adoc#_pcreatedeployenvironment,Creating a Deploy Environment>>), it will try to find that.
If not, it will look for the Deploy Script defined on the Project (<<ProjAdm_Projects.adoc#_projadmin_projectsoverview_editing,Editing Project Settings>>).

Then, it tries to find the Deploy Script in the decompressed Build result available in the Deploy Environment`'s Source Location.

If not found, it tries to copy the Deploy Script from the IKAN ALM Script Location as defined in the <<GlobAdm_System.adoc#_globadm_system_settings,System Settings>>.

If not found there either, the Verify Deploy Script Phase exits with status __Error__.

If found, the Verify Deploy Script Phase exits with status __Success__, and reports where it located the Deploy Script.

[[_phases_deployphases_executedeployscript]]
=== Execute Script Phase 
(((Phases ,Deploy Phases ,Execute Script))) 

The _Execute Script_ Phase executes the Deploy Script on the defined Machine using the specified Scripting Tool and the defined Deploy Parameters. 

It saves the Deploy log generated by the Deploy Script in the IKAN ALM database.

When the Deploy Script is executed successfully, the _Execute
Script_ Phase exits with status __Success__.
If not, it exits with status _Error_ and logs the errors on the _Phase Logs_ panel of the _Level
Request Detail_ screen (<<Desktop_LevelRequests.adoc#_desktop_lr_phaselogs_deployactions,Deploy Actions>>).

[[_phases_deployphases_cleanupbuidlresult]]
=== Cleanup Build Result Phase 
(((Phases ,Deploy Phases ,Cleanup Build Result))) 

The _Cleanup Build Result_ Phase deletes all files in the Deploy Environment`'s Source Location.

If the Deploy Environment has its Debug flag set to '`Yes`', the Cleanup Build Result Phase does nothing, and exits with status __Error__, reporting that the Debug flag was set in the Deploy Environment.

Next to Core Phases, you may define your own Phases in Global Administration (<<GlobAdm_Phases.adoc#_globadm_phases_creating,Creating a Phase Definition>>) and specify that they may be used on a Deploy Environment.
Once inserted into the workflow of a Deploy Environment, we call them __Custom Deploy__ Phases.

[[_phases_deployphases_customdeployphase]]
=== Custom Deploy Phase 
(((Phases ,Deploy Phases ,Custom Deploy Phase))) 

[NOTE]
====
The Display Name of a Custom Deploy Phase, as defined in Global Administration and provided by the creator of the Custom Phase, is used in the ALM interface when inserting it into a Deploy Environment or viewing the log on the __View Deploy Phases Log __screen.
So, the name displayed could be something like "`Update Database`" or "`Deploy to web server`".
====

The _Custom Deploy_ Phase executes a script on the IKAN ALM Agent Machine using the specified Scripting Tool and the defined Deploy Parameters.
The Display Name of this Phase and the executed script (alm.phase.mainScript) are specified in the definition of this Custom Phase in Global Administration.
The Scripting Tool (alm.phase.builder) that executes the script depends on the Execution Type of the Phase definition.
When this Execution Type differs from the Scripting Tool linked to the Deploy Environment, its value must be set after inserting this Phase into a Deploy Environment.

The _Custom Deploy_ Phase has been introduced from IKAN ALM 5.5 onwards.
The log generated by the script is saved in the IKAN ALM database.
Note that this Phase is never inserted into the default workflow of a Deploy Environment (i.e., when creating a new Deploy Environment from scratch).

When the script is executed successfully, the _Custom
Deploy_ Phase exits with status __Success__.
If not, it exits with status _Error_ and logs the errors on the _Phase Logs_ panel of the _Level
Request Detail_ screen (<<Desktop_LevelRequests.adoc#_desktop_lr_phaselogs_deployactions,Deploy Actions>>).

[NOTE]
====
A _Custom Deploy_ Phase may also be a Custom Level or Build Phase: the definition in Global Administration can also specify that it may be used on a Level or Build Environment.
====

