
== Project Administration Options 
(((Project Administration ,Project Management Options)))  (((Project Management Options))) 

Once you have selected a Project from the Projects Overview, the Project Administration options become available.
The available options depend on your access rights.

For each of the Project Administration options (except for _History Log_ and __Audit
Project__), the following submenu options are available: _Create_ and __Overview__.

To avoid repeating the same information in several places, all procedures for creating, editing and deleting elements will be described in detail for each _Create_ submenu option.
References will be made to this description for the other submenu options.

[cols="1,1", frame="topbot", options="header"]
|===
| Submenu option
| Description

|_[Project Name]_
|The first option on the Project Administration submenu refers to the name of the selected Project or to the Project to which the selected Project Stream belongs.

Select this option to return to the _Project
Info_ screen.

|History Log
|Select this option to view the History Log of the selected Project. <<#_projadm_historylog,>>

|Project Stream
a|This drop-down menu contains two options:

* _Create Branch_
+
Select this option to create a new Branch for this Project. <<#_projadmin_projectstream_createbranch,>>
* _Overview_
+
Select this option to switch to the _Project
Streams_ screen. <<#_projadm_projectstreams,>>

|Lifecycles
a|This drop-down menu contains the following options:

* _Create_
+
Select this option to create a new Lifecycle. <<#_plifecyclemgt_createlifecycle,>>
* Overview
+
Select this option to switch to the _Lifecycles
Overview_ screen. <<#_plifecyclemgt_screen,>>

|Levels
a|This drop-down menu contains the following options:

* _Create Build Level_
+
<<#_plevelenvmgt_createbuildlevel,>>
* _Create Test Level_
+
<<#_plevelenvmgt_createtestorproductionlevel,>>
* _Create Production Level_
+
<<#_plevelenvmgt_createtestorproductionlevel,>>
* _Overview_
+
<<#_plevelenvmgt_accessing,>>

|Build Environments
a|This drop-down menu contains the following options:

* _Create_
+
Select this option to create a new Build Environment for the selected Project. <<#_pcreatebuildenvironment,>>
* _Overview_
+
Select this option to switch to the Build Environment Overview for the selected Project. <<ProjAdm_BuildEnv.adoc#_buildenvironmentsoverview,The Build Environments Overview Screen>>
* _Build Parameters_
+
Select this option to manage Build parameters for the selected Project. <<#_projadm_environmentparameters,>>

|Deploy Environments
a|This drop-down menu contains the following options:

* _Create_
+
Select this option to create a new Deploy Environment for the selected Project. <<#_pcreatedeployenvironment,>>
* _Overview_
+
Select this option to switch to the Deploy Environment Overview for the selected Project. <<ProjAdm_DeployEnv.adoc#_projadm_deployenvironmentsoverview,Deploy Environments The Deploy Environments Overview Screen>>
* _Deploy Parameters_
+
Select this option to manage Deploy parameters for the selected Project. <<#_projadm_environmentparameters,>>

|Audit Project
|Select this option to switch to audit the selected Project. <<#_projadm_auditingprojects,>>
|===