
[[_subversiongeneralinformation]]
= Subversion - informations générales 
(((Subversion)))  (((Subversion ,Informations générales))) 

Cet appendice donne des informations générales concernant la configuration du Référentiel Subversion, ainsi que quelques exemples concrets et une section concernant les métapropriétés.

* <<App_Subversion.adoc#_sappc_repositoryconnection,Connexion au référentiel>>
* <<App_Subversion.adoc#_sappc_repositorydefinition,Définition du référentiel>>
* <<App_Subversion.adoc#_sappc_fetchmetaproperties,Collecte des métapropriétés>>


[[_sappc_repositoryconnection]]
== Connexion au référentiel 
(((Subversion ,Connexion au référentiel))) 

IKAN ALM se connecte au Référentiel via le Client SVN (Subversion) qui doit être installé sur le Serveur IKAN ALM.
Le chemin de commande indique l`'emplacement du Client SVN.

Un Référentiel Subversion est identifié par son URL de Référentiel, par exemple _\file:///path/to/repos_ ou _svn://servername_ ou __\http://my.domain/repos__.
Pour plus d`'informations, se référer au manuel en-ligne de Subversion "`Version Control with Subversion, chapter 2 - Basic Concepts`" localisé à http://svnbook.red-bean.com/en/1.7/svn.basic.version-control-basics.html[http://svnbook.red-bean.com/en/1.7/svn.basic.version-control-basics.html].
Le chapitre 7 de ce manuel montre un tableau concernant les URLs du Référentiel et une section concernant le Référentiel Subversion.

Dans la plupart des cas, un Identifiant Utilisateur et un Mot de passe doivent être saisis, sauf si le Référentiel n`'est pas protégé (par exemple: pour le protocole __svn__, _anon-access = write_ dans le fichier ``svnserver.conf``) ou si les identifiants de l`'utilisateur exécutant le Serveur Web d`'IKAN ALM ou le processus serveur de l`'application sont sauvegardés dans la zone Utilisateur privée d`'exécutions ( _~/.subversion/auth/_ ou __%APPDATA%/Subversion/Auth/__). Pour plus d`'informations, se référer également à http://svnbook.red-bean.com/en/1.7/svn.serverconfig.netmodel.html#svn.serverconfig.netmodel.credcache[http://svnbook.red-bean.com/en/1.7/svn.serverconfig.netmodel.html#svn.serverconfig.netmodel.credcache].

[[_sappc_repositorydefinition]]
== Définition du référentiel 
(((Subversion ,Définition du référentiel))) 

La définition de Subversion nécessite l`'utilisation de champs spécifiques pour permettre une configuration flexible de la structure de Référentiel Subversion (voir http://svnbook.red-bean.com/en/1.2/svn.reposadmin.projects.html#svn.reposadmin.projects.chooselayout[http://svnbook.red-bean.com/en/1.2/svn.reposadmin.projects.html#svn.reposadmin.projects.chooselayout]).

Dans les sections suivantes, vous trouverez des informations concernant:

* <<App_Subversion.adoc#_sappc_specificfields,Champs de configuration spécifiques>>
* <<App_Subversion.adoc#_sappc_layoutexamples,Exemples de structure>>


[[_sappc_specificfields]]
=== Champs de configuration spécifiques

Les champs spécifiques suivants ont été ajoutés à la définition de Subversion:

* Répertoire des projets (Trunk)
* Répertoire des versions (Tags)
* Structure du référentiel


==== Répertoire des projets (Trunk)

Le répertoire des projets (Trunk) est le répertoire du flux de développement principal ("`head`" ou "`main`"). La dénomination par défaut de ce répertoire est __trunk__, mais d`'autres dénominations sont permises, par exemple, _main_ ou __head__.

Ce répertoire peut se trouver directement en-dessous du chemin de référentiel ou peut être spécifique par projet en fonction des Paramètres saisis dans le champ _Structure du référentiel_ décrit ci-dessous.

[NOTE]
====
Le champ _Répertoire des projets (Trunk)_ ne peut rester vide que si le champ _Structure du référentiel_ contient la valeur __Orienté référentiel__.
Pour une structure de référentiel _Orientée projet_ ou __Orientée projet
unique__, le répertoire des projets doit être spécifié pour éviter des Construction continues infinies dans le cas où un Plan horaire serait défini pour une telle définition de référentiel (Le répertoire des versions faisant partie du répertoire des projets, le processus de balisage créerait une modification du répertoire des projets, ce qui engendrerait une boucle sans fin).
====

==== Répertoire des versions (Tags)

Le répertoire des versions (Tags) est l`'emplacement où IKAN ALM crée les Balises (appelés également des tags) après une Construction exécutée correctement.
La dénomination par défaut de ce répertoire est __tags__, mais d`'autres dénominations sont permises, par exemple, __tag__.

Ce répertoire peut se trouver directement en-dessous du chemin de référentiel, ou peut être spécifique par projet en fonction des Paramètres saisis dans le champ __Structure du référentiel__.

==== Structure du référentiel

La structure du référentiel par défaut est établie à __Orienté
projet__.
Les autres valeurs possibles sont: _Orienté référentiel_ et __Orienté
projet unique__.

Référez-vous aux <<App_Subversion.adoc#_sappc_layoutexamples,Exemples de structure>> pour plus d`'informations concernant la configuration des structures possibles.

[[_sappc_layoutexamples]]
=== Exemples de structure

Cette section décrit les structures de référentiel possibles ainsi qu`'une solution possible dans IKAN ALM pour un Référentiel Subversion.

[NOTE]
====
Les dénominations de répertoire utilisées (Trunk, Tags, Branches) sont arbitraires.
Si vous désirez appeler le répertoire des projets "`main`" ou "`head`", ou le répertoire des Branches "`stream`" ou 
 ., vous pouvez le faire librement.
====

==== Structure 1 (Orienté projet)

La structure dans le Référentiel Subversion:

[cols="1", frame="topbot"]
|===

|

/

/calc

/calc/trunk

/calc/branches

/calc/tags

/paint

/paint/trunk

/paint/branches

/paint/tags
|===


La définition dans IKAN ALM:

[NOTE]
====
URL = l`'URL de référentiel spécifié dans la définition de Subversion.
====

[cols="1,1,1", frame="topbot", options="header"]
|===
| 
| Description
| Valeur

|Répertoire des projets (Référentiel Subversion)
|Le répertoire des projets (Trunk) dans le Référentiel Subversion.
|trunk

|Répertoire des versions (Référentiel Subversion)
|Le répertoire des versions (Tags) dans le Référentiel Subversion.
|tags

|Structure du référentiel (Référentiel Subversion)
|Une des structures de référentiel possibles.
|Orienté projet

|Dénomination du Projet RCV (Définition du Projet)
|La dénomination du Projet dans le RCV.
|calc

|Validation du Projet (Définition du Projet)
|Si vous cliquez sur le bouton "`Vérifier le nom de projet dans le RCV`", l`'existence de ces répertoires sera vérifié.
|URL/calc/trunk

URL/calc/tags

|Récupération Branche Principale (Administration des Requêtes de Niveau)
|Le répertoire qui est récupéré en local pour la branche principale du projet dans la phase "`Extraction code`". 
|URL/calc/trunk

|Modèle de balise pour la Branche Principale (Aperçu détaillé d`'une Requête de Niveau)
|Modèle de balise généré après une Construction correctement exécutée pour une branche principale.
|URL/calc/tags/H_1-0_b1

|Identifiant de la Branche Secondaire dans le RCV (Définition de la Branche Secondaire)
|L`'identifiant de la Branche Secondaire telle que définie dans le RCV.
|/calc/branches/B_1-2

|Validation de la Branche Secondaire (Définition de Branches Secondaires)
|Si vous cliquez sur le bouton "`Vérifier le nom de branche dans le RCV`", l`'existence de ces répertoires sera vérifié.
|URL/calc/branches/B_1-2

|Récupération Branche Secondaire (Administration des Requêtes de Niveau)
|Le répertoire qui est récupéré en local pour la Branche Secondaire du projet dans la phase "`Extraction code`". 
|URL/calc/branches/B_1-2

|Modèle de balise pour la Branche Secondaire (Aperçu détaillé d`'une Requête de Niveau)
|Modèle de balise généré après une Construction correctement exécutée pour une Branche Secondaire.
|URL/calc/tags/B_1-2_b5
|===

==== Structure 2 (Orienté référentiel)

La structure dans le Référentiel Subversion:

[cols="1", frame="topbot"]
|===

|

/

/trunk

/trunk/calc

/trunk/paint

/tags/paint

/tags/calc

/branches
|===


La définition dans IKAN ALM:

[NOTE]
====
URL = l`'URL de référentiel spécifié dans la définition de Subversion.
====

[cols="1,1,1", frame="topbot", options="header"]
|===
| 
| Description
| Valeur

|Répertoire des projets (Référentiel Subversion)
|Le répertoire des projets (Trunk) dans le Référentiel Subversion.
|trunk

|Répertoire des versions (Référentiel Subversion)
|Le répertoire des versions (Tags) dans le Référentiel Subversion.
|tags

|Structure du référentiel (Référentiel Subversion)
|Une des structures de référentiel possibles.
|Orienté référentiel

|Dénomination du Projet RCV (Définition du Projet)
|La dénomination du Projet dans le RCV.
|calc

|Validation du Projet (Définition du Projet)
|Si vous cliquez sur le bouton "`Vérifier le nom de projet dans le RCV`", l`'existence de ces répertoires sera vérifié.
|URL/trunk/calc

URL/tags/calc

|Récupération Branche Principale (Administration des Requêtes de Niveau)
|Le répertoire qui est récupéré en local pour la branche principale du projet dans la phase "`Extraction code`". 
|URL/trunk/calc

|Modèle de balise pour la Branche Principale (Aperçu détaillé d`'une Requête de Niveau)
|Modèle de balise généré après une Construction correctement exécutée pour la branche principale.
|URL /tags/calc/H_1-0_b1

|Identifiant de la Branche Secondaire dans le RCV (Définition de la Branche Secondaire)
|L`'identifiant de la Branche Secondaire telle que définie dans le RCV.
|/branches/calc/B_1-2

|Validation de la Branche Secondaire (Définition de Branches Secondaires)
|Si vous cliquez sur le bouton "`Vérifier le nom de branche dans le RCV`", l`'existence de ces répertoires sera vérifié.
|URL/branches/calc/B_1-2

|Récupération Branche Secondaire (Administration des Requêtes de Niveau)
|Le répertoire qui est récupéré en local pour la Branche Secondaire du projet dans la phase "`Extraction code`". 
|URL/branches/calc/B_1-2

|Modèle de balise pour la Branche Secondaire (Aperçu détaillé d`'une Requête de Niveau)
|Modèle de balise généré après une Construction correctement exécutée pour une Branche Secondaire.
|URL /tags/calc/B_1-2_b5
|===

==== Structure 3 (Un référentiel = un Projet)

La structure dans le Référentiel Subversion:

[cols="1", frame="topbot"]
|===

|

/

/trunk

/tags

/branches
|===


La définition dans IKAN ALM:

[NOTE]
====
URL = l`'URL de référentiel spécifié dans la définition de Subversion.
====

[cols="1,1,1", frame="topbot", options="header"]
|===
| 
| Description
| Valeur

|Répertoire des projets (Référentiel Subversion)
|Le répertoire des projets (Trunk) dans le Référentiel Subversion.
|trunk

|Répertoire des versions (Référentiel Subversion)
|Le répertoire des versions (Tags) dans le Référentiel Subversion.
|tags

|Structure du référentiel (Référentiel Subversion)
|Une des structures de référentiel possibles.
|Orienté projet unique

|Dénomination du Projet RCV (Définition du Projet)
|La dénomination du Projet dans le RCV.
|vide

|Validation du Projet (Définition du Projet)
|Si vous cliquez sur le bouton "`Vérifier le nom de projet dans le RCV`", l`'existence de ces répertoires sera vérifié.
|URL/trunk

URL/tags

|Récupération Branche Principale (Administration des Requêtes de Niveau)
|Le répertoire qui est récupéré en local pour la branche principale du projet dans la phase "`Extraction code`". 
|URL/trunk

|Modèle de balise pour la Branche Principale (Aperçu détaillé d`'une Requête de Niveau)
|Modèle de balise généré après une Construction correctement exécutée pour la branche principale.
|URL /tags/H_1-0_b1

|Identifiant de la Branche Secondaire dans le RCV (Définition de la Branche Secondaire)
|L`'identifiant de la Branche Secondaire telle que définie dans le RCV.
|/branches/B1-2

|Validation de la Branche Secondaire (Définition de Branches Secondaires)
|Si vous cliquez sur le bouton "`Vérifier le nom de branche dans le RCV`", l`'existence de ces répertoires sera vérifié.
|URL/branches/B1-2

|Récupération Branche Secondaire (Administration des Requêtes de Niveau)
|Le répertoire qui est récupéré en local pour la Branche Secondaire du projet dans la phase "`Extraction code`". 
|URL/branches/B1-2

|Modèle de balise pour la Branche Secondaire (Aperçu détaillé d`'une Requête de Niveau)
|Modèle de balise généré après une Construction correctement exécutée pour une Branche Secondaire.
|URL /tags/B_1-2_b5
|===

==== Structure 4 (Orienté référentiel, pas de répertoirede projets)

La structure dans le Référentiel Subversion:

[cols="1", frame="topbot"]
|===

|

/

/calc (= répertoire des projets)

/paint (= répertoire des projets)

/tags/paint

/tags/calc

/branches
|===


La définition dans IKAN ALM:

[NOTE]
====
URL = l`'URL de référentiel spécifié dans la définition de Subversion.
====

[cols="1,1,1", frame="topbot", options="header"]
|===
| 
| Description
| Valeur

|Répertoire des projets (Référentiel Subversion)
|Le répertoire des projets (Trunk) dans le Référentiel Subversion.
|vide

|Répertoire des versions (Référentiel Subversion)
|Le répertoire des versions (Tags) dans le Référentiel Subversion.
|tags

|Structure du référentiel (Référentiel Subversion)
|Une des structures de référentiel possibles.
|Orienté référentiel

|Dénomination du Projet RCV (Définition du Projet)
|La dénomination du Projet dans le RCV.
|calc

|Validation du Projet (Définition du Projet)
|Si vous cliquez sur le bouton "`Vérifier le nom de projet dans le RCV`", l`'existence de ces répertoires sera vérifié.
|URL/calc

URL/tags/calc

|Récupération Branche Principale (Administration des Requêtes de Niveau)
|Le répertoire qui est récupéré en local pour la branche principale du projet dans la phase "`Extraction code`". 
|URL/calc

|Modèle de balise pour la Branche Principale (Aperçu détaillé d`'une Requête de Niveau)
|Modèle de balise généré après une Construction correctement exécutée pour une branche principale.
|URL /tags/calc/H_1-0_b1

|Identifiant de la Branche Secondaire dans le RCV (Définition de la Branche Secondaire)
|L`'identifiant de la Branche Secondaire telle que définie dans le RCV.
|/branches/calc/B_1-2

|Validation de la Branche Secondaire (Définition de Branches Secondaires)
|Si vous cliquez sur le bouton "`Vérifier le nom de branche dans le RCV`", l`'existence de ces répertoires sera vérifié.
|URL/branches/calc/B_1-2

|Récupération Branche Secondaire (Administration des Requêtes de Niveau)
|Le répertoire qui est récupéré en local pour la Branche Secondaire du projet dans la phase "`Extraction code`". 
|URL/branches/B1-2

|Modèle de balise pour la Branche Secondaire (Aperçu détaillé d`'une Requête de Niveau)
|Modèle de balise généré après une Construction correctement exécutée pour une Branche Secondaire.
|URL /tags/calc/B_1-2_b5
|===

[[_sappc_fetchmetaproperties]]
== Collecte des métapropriétés 
(((Subversion ,Collecte des métapropriétés))) 

Subversion offre des interfaces pour ajouter, modifier et supprimer des métadonnées versionnées de répertoires et de fichiers versionnés.
Ces métadonnées sont appelées des __propriétés__.
Pour plus d`'informations concernant l`'usage et la définition de ces propriétés reliées à des fichiers et à des répertoires, se référer au manuel en-ligne de Subversion "`Version Control with Subversion, Chapter 7 - Advanced properties`" localisé à http://svnbook.red-bean.com/en/1.2/svn.advanced.props.html[http://svnbook.red-bean.com/en/1.2/svn.advanced.props.html].

IKAN ALM permet l`'utilisation de ces propriétés lors des processus de construction et de déploiement.
Si la valeur "`Collecte des métapropriétés`" est __oui__, les étapes suivantes seront exécutées lors du processus de construction:


. Génération d`'un fichier de propriétés (vcr.properties)
+
A la fin de la phase "`Extraction code`", lors de l`'exécution d`'une Requête de Niveau, un fichier de propriétés `vcr.properties` sera généré dans le répertoire racine du code récupéré.
Ce fichier contient toutes les métapropriétés des fichiers de l`'URL récupéré (le répertoire des projets (trunk ou branches)). Le format suivant est utilisé:
+
``path.to.file.filename.propertyname=propertyvalue``
+
Il est évident que, si plusieurs métapropriétés sont reliées à un même fichier, plusieurs entrées seront créées dans le fichier ``vcr.properties``.
+
Quelques exemples:
+
Exemple 1: Une propriété nommée _register_ et une valeur de propriété _true_ pour le fichier _/bin/Musicbiz.dll_ résulteront par la ligne de propriété suivante: `bin.Musicbiz.dll.register= true`
+
Exemple 2: Deux propriétés _servletspecs=2.5_ et _unchangeable=true_ sont reliées au fichier __/MusicLib/WEB-INF/web.xml__.
Cela résultera par les lignes de propriété suivantes dans le fichier ``vcr.properties``.
+
``MusicLib.WEB-INF.web.xml.servletspecs=
2.5``
+
``MusicLib.WEB-INF.web.xml.unchangeable=
true``
. Transfert du fichier vcr.properties vers l`'emplacement Source de l`'Environnement de Construction
+
Pendant la phase "`Transfert Sources`" d`'un processus de construction, le fichier `vcr.properties` sera transféré vers l`'emplacement Source de l`'Environnement de Construction en même temps que les codes ou objets Sources récupérés depuis le répertoire des projets ou depuis le répertoire des versions de Subversion. 
+
Pour pouvoir appliquer les propriétés, le script de construction doit être adapté.
Par exemple, si vous utilisez un outil de script ANT, les propriétés peuvent être importées dans le script via la tâche __<property file="vcr.properties"/>__.
. Inclusion du fichier vcr.properties dans le résultat de construction
+
Si ces propriétés doivent également être disponibles lors d`'un processus de déploiement ultérieur, c`'est-à-dire sur un Environnement de Déploiement associé à cet Environnement de Construction, le fichier `vcr.properties` doit être inclus dans le résultat de construction.
+
Cela s`'accomplit en incluant une instruction de copie dans le script de construction qui copiera le fichier `vcr.properties` à partir de l`'emplacement Source (paramètre de construction prédéfini __Source__) vers l`'emplacement Cible (paramètre de construction prédéfini __target__) de l`'Environnement de Construction.
+
Ainsi, le fichier `vcr.properties` sera inclu dans le résultat de construction, et, par conséquent, il sera disponible pour le script de déploiement pendant le processus de déploiement de ce résultat de construction.

